os: linux
dist: focal
arch: ppc64le

compiler: gcc

branches:
  only:
  - travis-test
  
language: cpp

cache: ccache

addons:
  apt:
    sources:
      - sourceline: 'deb http://packages.icinga.com/ubuntu icinga-xenial main'
        key_url: 'https://packages.icinga.com/icinga.key'
    packages:
      - libboost1.67-dev
      - flex
      - bison
      - libssl-dev
      - libpq-dev
      - libmysqlclient-dev
      - libedit-dev
before_script:
  - arch=$(uname -m)
  - mkdir build
  - cd build
  - >
    cmake ..
    -DCMAKE_BUILD_TYPE=Debug
    -DICINGA2_UNITY_BUILD=Off
    -DCMAKE_INSTALL_PREFIX=/tmp/icinga2
    -DICINGA2_PLUGINDIR=/tmp/icinga2/sbin
    
script:
  - make
  - make test
  - make install
  - /tmp/icinga2/sbin/icinga2 --version
  - /tmp/icinga2/sbin/icinga2 daemon -C -DRunAsUser=$(id -u -n) -DRunAsGroup=$(id -g -n)
