os: linux
dist: focal
arch: ppc64le

compiler: gcc

branches:
  only:
  - travis-test
  
language: cpp

cache: ccache

addons:
  apt:
    packages:
      - rpm
      - rpmdevtools

before_script:
  - chmod +x icinga-build-package
  - chmod +x icinga-build-rpm-source
  - chmod +x functions-rpm.sh 
  - chmod +x functions-common.sh 
  - chmod +x run-retry-timeout
  - chmod +x run-timeout



script:
 - ./icinga-build-package
